name: Kwiki-Archive-SVK
version: 0.10
abstract: Kwiki Page Archival Using SVK
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  SVK: 0.23
  Kwiki: 0.35
  IO::All: 0.31
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
