name: Kwiki-Archive-SVK
version: 0.01
abstract: Kwiki Page Archival Using SVK
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.33
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
