name: Kwiki-Archive-SVK
version: 0.06
abstract: Kwiki Page Archival Using SVK
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  SVK: 0.17
  Kwiki: 0.33
  IO::All: 0.31
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
